## Learn String Manipulation by Creating a Cypher

Python is a powerful and popular programming language widely used for data science, data visualization, web development, game development, machine learning and more.

In this project, you'll learn fundamental programming concepts in Python, such as variables, functions, loops, and conditional statements. You'll use these to code your first programs.

In [1]:
#Caesar Cypher
text = 'Hello Zaira'
shift = 3

def caesar(message, offset):
    alphabet = 'abcdefghijklmnopqrstuvwxyz'
    encrypted_text = ''

    for char in message.lower():
        if char == ' ':
            encrypted_text += char
        else:
            index = alphabet.find(char)
            new_index = (index + offset) % len(alphabet)
            encrypted_text += alphabet[new_index]
    print('plain text:', message)
    print('encrypted text:', encrypted_text)

caesar(text, shift)
caesar(text, 13)

plain text: Hello Zaira
encrypted text: khoor cdlud
plain text: Hello Zaira
encrypted text: uryyb mnven


In [ ]:
text = 'mrttaqrhknsw ih puggrur'
custom_key = 'happycoding'

def vigenere(message, key, direction=1):
    key_index = 0
    alphabet = 'abcdefghijklmnopqrstuvwxyz'
    final_message = ''

    for char in message.lower():

        # Append any non-letter character to the message
        if not char.isalpha():
            final_message += char
        else:        
            # Find the right key character to encode/decode
            key_char = key[key_index % len(key)]
            key_index += 1

            # Define the offset and the encrypted/decrypted letter
            offset = alphabet.index(key_char)
            index = alphabet.find(char)
            new_index = (index + offset*direction) % len(alphabet)
            final_message += alphabet[new_index]
    
    return final_message

def encrypt(message, key):
    return vigenere(message, key)
    
def decrypt(message, key):
    return vigenere(message, key, -1)

print(f'\nEncrypted text: {text}')
print(f'Key: {custom_key}')
decryption = decrypt(text, custom_key)
print(f'\nDecrypted text: {decryption}\n')

wcesc mpgkh


We can use `pass` as a placeholder while creating code. The function will be passed over

## Work with letters and numbers by implementing the Luhn Algorithm

The Luhn Algorithm is widely used for error-checking in various applications, such as verifying credit card numbers.

By building this project, you'll gain experience working with numerical computations and string manipulation.


Python comes with built-in classes that can help us with string manipulation. One of them is the str class. It has a method called `maketrans` that can help us create a translation table. This table can be used to replace characters in a string:
```
str.maketrans({'t': 'c', 'l': 'b'})
```

Defining the translation does not in itself translate the string. The translate method must be called on the string to be translated with the translation table as an argument:
Example Code
```
my_string = "tamperlot"
translation_table = str.maketrans({'t': 'c', 'l': 'b'})
translated_string = my_string.translate(translation_table)
```

In [3]:
def verify_card_number(card_number):
    pass

def main():
    card_number = '4111-1111-4555-1142'
    card_translation = str.maketrans({'-': '', ' ': ''})
    translated_card_number = card_number.translate(card_translation)

    print(translated_card_number)

    verify_card_number(translated_card_number)

main()

4111111145551142


The Luhn algorithm is as follows:
1. From the right to left, double the value of every second digit; if the product is greater than 9, sum the digits of the products.
2. Take the sum of all the digits.
3. If the sum of all the digits is a multiple of 10, then the number is valid; else it is not valid.

Assume an example of an account number "7992739871" that will have a check digit added, making it of the form 7992739871x:
Example Code
```
Account number      7   9  9  2  7  3  9   8  7  1  x
Double every other  7  18  9  4  7  6  9  16  7  2  x
Sum 2-char digits   7   9  9  4  7  6  9   7  7  2  x
```

Additionally, another way you can reverse a string is with `temp_string[::-1]`

In [5]:
def verify_card_number(card_number):
    sum_of_odd_digits = 0
    card_number_reversed = card_number[::-1]
    odd_digits = card_number_reversed[::2]

    for digit in odd_digits:
        sum_of_odd_digits += int(digit)

    sum_of_even_digits = 0
    even_digits = card_number_reversed[1::2]
    for digit in even_digits:
        number = int(digit) * 2
        if number >= 10:
            number = (number // 10) + (number % 10)
        sum_of_even_digits += number
    total = sum_of_odd_digits + sum_of_even_digits
    return total % 10 == 0

def main():
    card_number = '4111-1111-4555-1142'
    card_translation = str.maketrans({'-': '', ' ': ''})
    translated_card_number = card_number.translate(card_translation)

    if verify_card_number(translated_card_number):
        print('VALID!')
    else:
        print('INVALID!')

main()

VALID!


## Learn the Lambda Function by building an Expense Tracker

Adding onto what we learned about lists earlier: the `insert` method can add an element at any position in a list. The first argument is the position at which the element has to be added, and the second argument is the element to add. For example, here's how to add a new element in the third position of example_list:

Example Code
```
example_list = [4, 5, 6, 7]
example_list.insert(2, 5.5)
print(example_list) # [4, 5, 5.5, 6, 7]
```

The `pop()` method can be used to remove an element from a list. By default, it removes the last element of the list. You can pass an index as the argument to the method, and it will remove the element at the given index.
Example Code
```
fruits_list = ["cherry", "lemon", "tomato", "apple", "orange"]
fruits_list.pop(2)
print(fruits_list) # ["cherry", "lemon", "apple", "orange"]
```

Lambda functions are brief, anonymous functions in Python, ideal for simple, one-time tasks. They are defined by the `lambda` keyword, and they use the following syntax:
Example Code
```
lambda x: expr
```
In the example above, `x` represents a parameter to be used in the expression `expr`, and it acts just like any parameter in a traditional function. `expr` is the expression that gets evaluated and returned when the lambda function is called.

In [ ]:
test = lambda x: x * 2
print(test(3))
# the lambda function and it's expression get saved to the test var and can be called like a
    # normal function. When you enter a value into the function call, it gets entered into the
    # expression as the varible

6


Lambda functions can be valuably combined with the map() function, which executes a specified function for each element in a collection of objects, such as a list:

Example Code
```
map(lambda x: x * 2, [1, 2, 3])
map(function, [values])
```
The function to execute is passed as the first argument, and the iterable is passed as the second argument.

The result of the example above would be [2, 4, 6], where each item in the list passed to map() has been doubled by the action of the lambda function.

To actually read the result of the map, we have to convert the map to a list.

In [3]:
test = (lambda x: x * 2)
print(map(test, [2,3,5,8]))
print(list(map(test, [2,3,5,8])))

[4, 6, 10, 16]


`sum()` works the same way it does in MATLAB

The `filter()` function allows you to select items from an iterable, such as a list, based on the output of a function:

Example Code
```
filter(my_function, my_list)
```
`filter()` takes a function as its first argument and an iterable as its second argument. It returns an iterator, which is a special object that enables you to iterate over the elements of a collection, like a list.

The result of the example above is an iterator containing the elements of `my_list` for which `my_function` returns `True`.

In [ ]:
## Complete expense tracker: 

def add_expense(expenses, amount, category):
    expenses.append({'amount': amount, 'category': category})
    
def print_expenses(expenses):
    for expense in expenses:
        print(f'Amount: {expense["amount"]}, Category: {expense["category"]}')
    
def total_expenses(expenses):
    return sum(map(lambda expense: expense['amount'], expenses))
    
def filter_expenses_by_category(expenses, category):
    return filter(lambda expense: expense['category'] == category, expenses)
    

def main():
    expenses = []
    while True:
        print('\nExpense Tracker')
        print('1. Add an expense')
        print('2. List all expenses')
        print('3. Show total expenses')
        print('4. Filter expenses by category')
        print('5. Exit')
       
        choice = input('Enter your choice: ')

        if choice == '1':
            amount = float(input('Enter amount: '))
            category = input('Enter category: ')
            add_expense(expenses, amount, category)

        elif choice == '2':
            print('\nAll Expenses:')
            print_expenses(expenses)
    
        elif choice == '3':
            print('\nTotal Expenses: ', total_expenses(expenses))
    
        elif choice == '4':
            category = input('Enter category to filter: ')
            print(f'\nExpenses for {category}:')
            expenses_from_category = filter_expenses_by_category(expenses, category)
            print_expenses(expenses_from_category)
    
        elif choice == '5':
            print('Exiting the program.')
            break

main()


Expense Tracker
1. Add an expense
2. List all expenses
3. Show total expenses
4. Filter expenses by category
5. Exit

Expense Tracker
1. Add an expense
2. List all expenses
3. Show total expenses
4. Filter expenses by category
5. Exit

All Expenses:
Amount: 29.99, Category: misc

Expense Tracker
1. Add an expense
2. List all expenses
3. Show total expenses
4. Filter expenses by category
5. Exit

Expense Tracker
1. Add an expense
2. List all expenses
3. Show total expenses
4. Filter expenses by category
5. Exit

All Expenses:
Amount: 29.99, Category: misc
Amount: 35.67, Category: bills

Expense Tracker
1. Add an expense
2. List all expenses
3. Show total expenses
4. Filter expenses by category
5. Exit
Exiting the program.


## Learn Python List Comprehension by Building a Case Convertor Program
List Comprehension is a way to construct a new Python list from an iterable types: lists, tuples, and strings. All without using a for loop or the `.append()` list method.

In this project, you'll write a program that takes a string formatted in Camel Case or Pascal Case, then converts it into Snake Case.

The project has two phases: first you'll use a for loop to implement the program. Then you'll learn how to use List Comprehension instead of a loop to achieve the same results.

By this point, the variable snake_cased_char_list holds the list of converted characters. To combine these characters into a single string, you can utilize the `.join()` method.

The `join` method works by concatenating each element of a list into a string, separated by a designated string, known as the separator.

Example Code
```
result_string = ''.join(characters)
```
The example above joins together the elements of the characters list into a single string where each element is concatenated together using an empty string as the separator.

In [ ]:
def convert_to_snake_case(pascal_or_camel_cased_string):
    snake_cased_char_list = []
    for char in pascal_or_camel_cased_string:
        if char.isupper():
            converted_character = '_' + char.lower()
            snake_cased_char_list.append(converted_character)
        else:
            snake_cased_char_list.append(char)
    snake_cased_string = ''.join(snake_cased_char_list)

In pascal case, strings begin with a capital letter. After converting all the characters to lowercase and adding an underscore to them, there's a chance of having an extra underscore at the start of your string.

The easiest way to fix this is by using the .strip() string method, which removes from a string any leading or trailing characters among a set of characters passed as its argument. For example:

Example Code
```
original_string = "_example_string_"

clean_string = original_string.strip('_')
```
The strip() method is applied to original_string. This removes any leading and trailing underscore. The result of the example above would be the string 'example_string'.

In [ ]:
## Using a for loop to iterate
def convert_to_snake_case(pascal_or_camel_cased_string):
    snake_cased_char_list = []
    for char in pascal_or_camel_cased_string:
        if char.isupper():
            converted_character = '_' + char.lower()
            snake_cased_char_list.append(converted_character)
        else:
            snake_cased_char_list.append(char)
    snake_cased_string = ''.join(snake_cased_char_list)
    
    # Strip unnecessary _ from beginning of string if from Pascal Case
    clean_snake_cased_string = snake_cased_string.strip('_')
    return clean_snake_cased_string

After joining the elements of the list `snake_cased_char_list`, you will need to remove any leading or trailing underscores from the resulting string. For this, use the `strip` method with the underscore character `_` as an argument.

Method calls can be chained together, which means that the result of one method call can be used as the object for another method call.

Example Code
```
words_list = ['hello', 'world', 'this', 'is', 'chained', 'methods']
result = ' '.join(words_list).upper()
```
In the example above, the `.upper()` method is chained to `' '.join(words_list)`, therefore `.upper() `is called on the result of the `.join()` call.

In [ ]:
''.join(snake_cased_char_list).strip('_')

In Python, a list comprehension is a construct that allows you to generate a new list by applying an expression to each item in an existing iterable and optionally filtering items with a condition. Apart from being briefer, list comprehensions often run faster.

A basic list comprehension consists of an expression followed by a for clause:

Example Code
```
spam = [i * 2 for i in iterable]
```
The above uses the variable `i` to iterate over iterable. Each elements of the resulting list is obtained by evaluating the expression `i * 2` at the current iteration.

In this step, you need to fill the empty list `snake_cased_char_list` using the list comprehension syntax.

In [ ]:
snake_cased_char_list = ['_' + char.lower() for char in pascal_or_camel_cased_string]

List comprehensions accept conditional statements, to evaluate the provided expression only if certain conditions are met:

Example Code
```
spam = [i * 2 for i in iterable if i > 0]
```
As you can see from the output, the list of characters generated from `pascal_or_camel_cased_string` has been joined. Since the expression inside the list comprehension is evaluated for each character, the result is a lowercase string with all the characters separated by an underscore.

In [ ]:
snake_cased_char_list = ['_' + char.lower() for char in pascal_or_camel_cased_string if char.isupper()]

Still, the final result is not exactly what you want to achieve. You need to execute a different expression for the characters filtered out by the `if` clause. You'll use an `else` clause for that:

Example Code
```
spam = [i * 2 if i > 0 else -1 for i in iterable]
```
Note that, differently from the `if` clause, the `if/else` construct must be placed between the expression and the `for` keyword.

In [ ]:
snake_cased_char_list = ['_' + char.lower() if char.isupper() else char for char in pascal_or_camel_cased_string]

Final result of case convertor program

In [5]:
def convert_to_snake_case(pascal_or_camel_cased_string):

    snake_cased_char_list = [
        '_' + char.lower() if char.isupper()
        else char
        for char in pascal_or_camel_cased_string
    ]

    return ''.join(snake_cased_char_list).strip('_')

def main():
    print(convert_to_snake_case('IAmAPascalCasedString'))

main()

i_am_a_pascal_cased_string


## Learn the Bisection Method by Finding the Square Root of a Number
Numerical methods are used to approximate solutions to mathematical problems that are difficult or impossible to solve analytically.

In this project, you will explore the numerical method of bisection to find the square root of a number by iteratively narrowing down the possible range of values that contain the square root.

The `raise` statement allows you to force a specific exception to occur. It consists of the `raise` keyword followed by the exception type, and enables you to provide a custom error message:

Example Code
```
raise ValueError("Invalid value")
```
When the code above runs, a `ValueError` is raised and the message `"Invalid value"` is shown to the user.

In [ ]:
raise ValueError('Square root of negative number is not defined in real numbers')

In Python, the `max()` function returns the largest of the input values.

Example Code
```
max(1, 2, 3) # Output: 3
```
The variables `low` and `high` will be used to define the initial interval where the square root lies.

Also if you have to initialize a variable for an integer or float, you can set it to `None`

Now you'll repeatedly narrow down the interval by finding the midpoint of the current interval and comparing the square of the midpoint with the target value.

For that, inside the `else` block, create a `for` loop that runs up to `max_iterations times`.

For your loop, use the `range` function, which generates a sequence of numbers you can iterate over. The syntax is `range(start, stop, step)`, where `start` is the starting integer (inclusive), `stop` is the last integer (not inclusive), and `step` is the difference between a number and the previous one in the sequence.

Also, use `_` as a loop variable. The `_` acts as a placeholder and is useful when you need to use a variable but don't actually need its value.

If you are counting up from 0 with a step of 1, you can just set the range to the final integer.

In [ ]:
for _ in range(max_iterations):
    pass

A reminder of the mathematical operators:
`**` is in place of `^`

Also `abs()` is the same

In [ ]:
for _ in range(max_iterations):
    mid = (low + high) / 2
    square_mid = mid ** 2

Final version of bisection function

In [ ]:
def square_root_bisection(square_target, tolerance=1e-7, max_iterations=100):
    if square_target < 0:
        raise ValueError('Square root of negative number is not defined in real numbers')
    if square_target == 1:
        root = 1
        print(f'The square root of {square_target} is 1')
    elif square_target == 0:
        root = 0
        print(f'The square root of {square_target} is 0')

    else:
        low = 0
        high = max(1, square_target)
        root = None
        
        for _ in range(max_iterations):
            mid = (low + high) / 2
            square_mid = mid**2

            if abs(square_mid - square_target) < tolerance:
                root = mid
                break

            elif square_mid < square_target:
                low = mid
            else:
                high = mid

        if root is None:
            print(f"Failed to converge within {max_iterations} iterations.")
    
        else:   
            print(f'The square root of {square_target} is approximately {root}')
    
    return root

N = 16
square_root_bisection(N)

The square root of 16 is approximately 4.0


4.0

## Certification Project: Build an Arithmetic Formatter 
Students in primary school often arrange arithmetic problems vertically to make them easier to solve. For example, "235 + 52" becomes:
```
  235
+  52
-----
```
Finish the arithmetic_arranger function that receives a list of strings which are arithmetic problems, and returns the problems arranged vertically and side-by-side. The function should optionally take a second argument. When the second argument is set to True, the answers should be displayed.

Function Call:
```
arithmetic_arranger(["32 + 698", "3801 - 2", "45 + 43", "123 + 49"])
```
Output:
```
   32      3801      45      123
+ 698    -    2    + 43    +  49
-----    ------    ----    -----
```
Function Call:
```
arithmetic_arranger(["32 + 8", "1 - 3801", "9999 + 9999", "523 - 49"], True)
```
Output:
```
  32         1      9999      523
+  8    - 3801    + 9999    -  49
----    ------    ------    -----
  40     -3800     19998      474
```

### Rules:
The function will return the correct conversion if the supplied problems are properly formatted, otherwise, it will return a string that describes an error that is meaningful to the user.

Situations that will return an error:
* If there are too many problems supplied to the function. The limit is five, anything more will return: 'Error: Too many problems.'
* The appropriate operators the function will accept are addition and subtraction. Multiplication and division will return an error. Other operators not mentioned in this bullet point will not need to be tested. The error returned will be: "Error: Operator must be '+' or '-'."
* Each number (operand) should only contain digits. Otherwise, the function will return: 'Error: Numbers must only contain digits.'
* Each operand (aka number on each side of the operator) has a max of four digits in width. Otherwise, the error string returned will be: 'Error: Numbers cannot be more than four digits.'

If the user supplied the correct format of problems, the conversion you return will follow these rules:
* There should be a single space between the operator and the longest of the two operands, the operator will be on the same line as the second operand, both operands will be in the same order as provided (the first will be the top one and the second will be the bottom).
* Numbers should be right-aligned.
* There should be four spaces between each problem.
* There should be dashes at the bottom of each problem. The dashes should run along the entire length of each problem individually. (The example above shows what this should look like.)

Note: open the browser console with F12 to see a more verbose output of the tests.


In [ ]:
def check_errors(problems):
    # Check for error: List must have max 5 problems
    if len(problems) > 5:
        raise ValueError('Error: Too many problems.')
    
    all_first_operands = []
    all_operators = []
    all_second_operands = []
    
    for problem in problems:
        first_operand = ""
        second_operand = ""
        operator_index = None
        
        remove_spaces = str.maketrans({' ':''})
        problem = problem.translate(remove_spaces)    # Remove spaces from statement if any exist
        
        # Check for error: Only '+' or '-' operators allowed in problems
        if not (problem.find('*') == -1) or not (problem.find('/') == -1):  # If not '+' or '-', print ValueError
            raise ValueError("Error: Operator must be '+' or '-'.")
        # Else '+' or '-' exists, save index and operator to corresponding vars
        elif not problem.find('+') == -1:
            operator_index = problem.find('+')
            all_operators.append(problem[operator_index])
        else:
            operator_index = problem.find('-')
            all_operators.append(problem[operator_index])

        # Save first operand and second operand to individual vars
        first_operand = problem[:operator_index]
        second_operand = problem[operator_index+1:]
        
        # Check for error: Problem has more than 2 operands
        if not (second_operand.find('+') == -1) or not (second_operand.find('-') == -1):
            raise ValueError('Error: Problem is too long.')
        
        # Check for error: Problems can only contain digits.
        if not first_operand.isdigit() or not second_operand.isdigit():
            raise ValueError('Error: Numbers must only contain digits.')
        
        # Check for error: Operators must have a maximum of 4 digits
        if len(first_operand) > 4 or len(second_operand) > 4:
            raise ValueError('Error: Numbers cannot be more than four digits.')
        
        # Append values to variables to return
        all_first_operands.append(first_operand)
        all_second_operands.append(second_operand)
    
    return all_first_operands, all_operators, all_second_operands


def arithmetic_arranger(problems, show_answers=False):
    # Initialize empty variables
    first_spaces = ''
    second_spaces = ''
    top_line = ''
    middle_line = ''
    bottom_line = ''
    answer = ''
    full_top_line = []
    full_middle_line = []
    full_bottom_line = []
    full_answer_line = []
    arranged_arithmetic = []
    
    
    # See if any of the problems result in an error
    first_operands, operators, second_operands = check_errors(problems)
    
    # Enter 4 spaces between each problem
    space_problems = 4 * ' '
    
    for index in range(len(operators)):        
        # Determine longest operand
        difference = len(first_operands[index]) - len(second_operands[index])
        
        # Right align numbers
            # 1 space between operator and longest of 2 operands
        if difference > 0:
            first_spaces = 2 * ' '
            second_spaces = (difference + 1) * ' '
        elif difference < 0:
            first_spaces = (abs(difference) + 2) * ' '
            second_spaces = ' '
        else:
            first_spaces = 2 * ' '
            second_spaces = ' '
        
        top_line = first_spaces + first_operands[index]
        middle_line = operators[index] + second_spaces + second_operands[index]    # Operator in same line as second operand
        bottom_line = len(top_line) * '-'    # Dashes along entire length of each problem individually

        # If we need to print answers: 
        if show_answers:
            if operators[index] == '+':
                answer = f"{int(first_operands[index]) + int(second_operands[index])}"
            else:
                answer = f"{int(first_operands[index]) - int(second_operands[index])}"
            # Determine number of spaces needed to right align answer
            answer = (len(bottom_line) - len(answer)) * ' ' + answer
        
        if index < (len(operators) - 1):
            full_top_line += (top_line + space_problems)
            full_middle_line += (middle_line + space_problems)
            full_bottom_line += (bottom_line + space_problems)
            if show_answers:
                full_answer_line += (answer + space_problems)
        else:
            full_top_line += (top_line + '\n')
            full_middle_line += (middle_line + '\n')
            if show_answers:
                full_bottom_line += (bottom_line + '\n')
                full_answer_line += (answer)
            else:
                full_bottom_line += (bottom_line)
            
    
    arranged_arithmetic = full_top_line + full_middle_line + full_bottom_line + full_answer_line
    return ''.join(arranged_arithmetic)

print(f'\n{arithmetic_arranger(["3801 - 2", "123 + 49"])}')
print(f'\n{arithmetic_arranger(["44 + 815", "909 - 2", "45 + 43", "123 + 49", "888 + 40", "653 + 87"])}')


  3801      123
-    2    +  49
------    -----


ValueError: Error: Too many problems.

### Tests:
1. `arithmetic_arranger(["3801 - 2", "123 + 49"])` should return `  3801      123\n-    2    +  49\n------    -----`.
2. `arithmetic_arranger(["1 + 2", "1 - 9380"])` should return `  1         1\n+ 2    - 9380\n---    ------`.
3. `arithmetic_arranger(["3 + 855", "3801 - 2", "45 + 43", "123 + 49"])` should return `    3      3801      45      123\n+ 855    -    2    + 43    +  49\n-----    ------    ----    -----`.
4. `arithmetic_arranger(["11 + 4", "3801 - 2999", "1 + 2", "123 + 49", "1 - 9380"])` should return `  11      3801      1      123         1\n+  4    - 2999    + 2    +  49    - 9380\n----    ------    ---    -----    ------`.
5. `arithmetic_arranger(["44 + 815", "909 - 2", "45 + 43", "123 + 49", "888 + 40", "653 + 87"])` should return `'Error: Too many problems.'`.
6. `arithmetic_arranger(["3 / 855", "3801 - 2", "45 + 43", "123 + 49"])` should return `"Error: Operator must be '+' or '-'."`.
7. `arithmetic_arranger(["24 + 85215", "3801 - 2", "45 + 43", "123 + 49"])` should return `'Error: Numbers cannot be more than four digits.'`.
8. `arithmetic_arranger(["98 + 3g5", "3801 - 2", "45 + 43", "123 + 49"])` should return `'Error: Numbers must only contain digits.'`.
9. `arithmetic_arranger(["3 + 855", "988 + 40"], True)` should return`     3      988\n+ 855    +  40\n-----    -----\n  858     1028`.
10. `arithmetic_arranger(["32 - 698", "1 - 3801", "45 + 43", "123 + 49", "988 + 40"], True)` should return `   32         1      45      123      988\n- 698    - 3801    + 43    +  49    +  40\n-----    ------    ----    -----    -----\n -666     -3800      88      172     1028`.

## FreeCodeCamp doesn't like my ValueError statements.
Convert to a single function that returns the strings instead of raising ValueErrors

In [ ]:
def check_errors(problems):
    # Check for error: List must have max 5 problems
    if len(problems) > 5:
        raise ValueError('Error: Too many problems.')
    
    all_first_operands = []
    all_operators = []
    all_second_operands = []
    
    for problem in problems:
        first_operand = ""
        second_operand = ""
        operator_index = None
        
        remove_spaces = str.maketrans({' ':''})
        problem = problem.translate(remove_spaces)    # Remove spaces from statement if any exist
        
        # Check for error: Only '+' or '-' operators allowed in problems
        if not (problem.find('*') == -1) or not (problem.find('/') == -1):  # If not '+' or '-', print ValueError
            raise ValueError("Error: Operator must be '+' or '-'.")
        # Else '+' or '-' exists, save index and operator to corresponding vars
        elif not problem.find('+') == -1:
            operator_index = problem.find('+')
            all_operators.append(problem[operator_index])
        else:
            operator_index = problem.find('-')
            all_operators.append(problem[operator_index])

        # Save first operand and second operand to individual vars
        first_operand = problem[:operator_index]
        second_operand = problem[operator_index+1:]
        
        # Check for error: Problem has more than 2 operands
        if not (second_operand.find('+') == -1) or not (second_operand.find('-') == -1):
            raise ValueError('Error: Problem is too long.')
        
        # Check for error: Problems can only contain digits.
        if not first_operand.isdigit() or not second_operand.isdigit():
            raise ValueError('Error: Numbers must only contain digits.')
        
        # Check for error: Operators must have a maximum of 4 digits
        if len(first_operand) > 4 or len(second_operand) > 4:
            raise ValueError('Error: Numbers cannot be more than four digits.')
        
        # Append values to variables to return
        all_first_operands.append(first_operand)
        all_second_operands.append(second_operand)
    
    return all_first_operands, all_operators, all_second_operands


def arithmetic_arranger(problems, show_answers=False):
    # Initialize empty variables
    first_spaces = ''
    second_spaces = ''
    top_line = ''
    middle_line = ''
    bottom_line = ''
    answer = ''
    full_top_line = []
    full_middle_line = []
    full_bottom_line = []
    full_answer_line = []
    arranged_arithmetic = []
    
    
    # See if any of the problems result in an error
    first_operands, operators, second_operands = check_errors(problems)
    
    # Enter 4 spaces between each problem
    space_problems = 4 * ' '
    
    for index in range(len(operators)):        
        # Determine longest operand
        difference = len(first_operands[index]) - len(second_operands[index])
        
        # Right align numbers
            # 1 space between operator and longest of 2 operands
        if difference > 0:
            first_spaces = 2 * ' '
            second_spaces = (difference + 1) * ' '
        elif difference < 0:
            first_spaces = (abs(difference) + 2) * ' '
            second_spaces = ' '
        else:
            first_spaces = 2 * ' '
            second_spaces = ' '
        
        top_line = first_spaces + first_operands[index]
        middle_line = operators[index] + second_spaces + second_operands[index]    # Operator in same line as second operand
        bottom_line = len(top_line) * '-'    # Dashes along entire length of each problem individually

        # If we need to print answers: 
        if show_answers:
            if operators[index] == '+':
                answer = f"{int(first_operands[index]) + int(second_operands[index])}"
            else:
                answer = f"{int(first_operands[index]) - int(second_operands[index])}"
            # Determine number of spaces needed to right align answer
            answer = (len(bottom_line) - len(answer)) * ' ' + answer
        
        if index < (len(operators) - 1):
            full_top_line += (top_line + space_problems)
            full_middle_line += (middle_line + space_problems)
            full_bottom_line += (bottom_line + space_problems)
            if show_answers:
                full_answer_line += (answer + space_problems)
        else:
            full_top_line += (top_line + '\n')
            full_middle_line += (middle_line + '\n')
            if show_answers:
                full_bottom_line += (bottom_line + '\n')
                full_answer_line += (answer)
            else:
                full_bottom_line += (bottom_line)
            
    
    arranged_arithmetic = full_top_line + full_middle_line + full_bottom_line + full_answer_line
    return ''.join(arranged_arithmetic)

print(f'\n{arithmetic_arranger(["3801 - 2", "123 + 49"])}')
print(f'\n{arithmetic_arranger(["44 + 815", "909 - 2", "45 + 43", "123 + 49", "888 + 40", "653 + 87"])}')


  3801      123
-    2    +  49
------    -----


ValueError: too many values to unpack (expected 3)